### PR TITLE
Fixed a bug for whole word masking

### PR DESCRIPTION
**Pull request by TianhaoFu**
Hi，nice work. 
And I found a bug when using your repository.

For the original wwm policy, the implementation is to first iterate through each word inside a phrase, and then use a mask token to replace the original token for some words and a random token for others based on the probability. This implementation results in inconsistent replacement rules for each word inside a phrase. The correct way to experiment would be to first determine the probability and then iterate through each word within the phrase. This ensures that the substitution rule is consistent for each word within a phrase.

:)

---
你好，很棒的工作。
唯一一个问题是我在使用你们的仓库时发现了一个小bug。

针对whole word masking策略，你们的仓库实现方式为首先遍历一个词组内部的每一个字，生成概率决定有的字使用mask token替换原始token，有的字使用随机替换原始token。这种实现方式会导致一个词组内部的每一个字替换法则不一致。正确的实验方式应该为首先确定概率，之后遍历词组内部的每一个字。这样可确保一个词组内部的每一个字替换法则一致。

### CODE REVIEW

**Comment by TianhaoFu** [comment]
Hi, I came to the conclusion after reading [macbert](https://arxiv.org/abs/2004.13922) that the author's wwm is mask in phrases, without looking at the source code to confirm. I did experiments on my own model and concluded that randomization by word is about as effective as mask by phrase.
:)


---
你好，我是在看完macbert论文以后，得出结论作者的wwm是以词组为单位进行mask，没有看源码确认。之后我在自己的模型上做了实验，结论是以字为单位进行随机与以词组为单位进行mask的效果差不多。

wwm in macbert

---
PS:
我觉得一般看wwm都会认为是以词组单位进行mask把

**Comment by hhou435** [comment]
Hello, I think [M] in the paper represents the use of mask strategy for this word, rather than replacing the word with [MASK] token.
In addition, the author of macbert has also maintained the same method as Google when implementing the wwm strategy of Chinese-BERT-wwm. 

您好，我认为论文中的[M]代表对此单词使用mask策略，而不是把单词替换成[MASK] token。
另外，macbert的作者在实现Chinese-BERT-wwm的wwm策略时，也保持了与谷歌实现的方法一致。
细节可以参考https://github.com/ymcui/Chinese-BERT-wwm/issues/4

**Comment by Embedding** [comment]
Thank you for your suggestion, and you can give us your email if it is convenient for you. We can discuss and seek your more code contributions. @TianhaoFu

**Comment by TianhaoFu** [comment]
> Thank you for your suggestion, and you can give us your email if it is convenient for you. We can discuss and seek your more code contributions. @TianhaoFu

OK~

**Pull request closed without merging**
